databases:
  - name: ScorpionData
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: Scorpion 
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 ser.py & python3 -m JoKeRUB 
    region: frankfurt
    envVars:
      - key: BOT_USERNAME
        sync: false
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ScorpionData
          property: connectionString   
    autoDeploy: false
